[package]
name = "burgundy"
version = "0.1.1"
authors = ["joseph.lenton@askattest.com <joseph.lenton@askattest.com>"]
description = "Library for building API service bindings"
repository = "https://github.com/JosephLenton/burgundy"
license = "MIT"

[dependencies]
hyper = "0.12.5"
failure = "0.1.1"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.22"

